//Roo/mailer/Body.js
Roo.mailer=Roo.mailer||{};Roo.mailer.Body=function(A){Roo.mailer.Body.superclass.constructor.call(this,A);Roo.get(document.body).attr({leftmargin:0,marginwidth:0,topmargin:0,marginheight:0,offset:0});};Roo.extend(Roo.mailer.Body,Roo.bootstrap.Component,{cls:'',getAutoCreate:function(){var A={tag:'center',cn:[{tag:'table',border:0,cellpadding:0,cellspacing:0,height:'100%',align:'center',cls:'roo-m-body-table '+this.cls,cn:[{tag:'tr',cn:[{tag:'td',align:'center',valight:'top',cls:'roo-m-body-cell'}]}]}]};return A;},getChildContainer:function(){return this.el.select('.roo-m-body-cell').first();}});
//Roo/mailer/Block.js
Roo.mailer.Block=function(A){Roo.mailer.Block.superclass.constructor.call(this,A);};Roo.extend(Roo.mailer.Block,Roo.bootstrap.Component,{cls:'',html:'',blocktype:'header',getAutoCreate:function(){var tr={tag:'tr',cls:'roo-m-block-tr'};if(this.blocktype!='column-container'){tr.cn=[{tag:'td',align:'center',valight:'top',cls:'roo-m-'+this.blocktype+'-content',html:this.html}]}var cfg={tag:'table',border:0,cellpadding:0,cellspacing:0,width:'100%',align:'center',cls:'roo-m-'+this.blocktype+' '+this.cls,cn:[tr]};return cfg;},getChildContainer:function(){if(this.blogtype=='column-container'){var A=this.select('roo-m-block-tr',true).first();return A.createChild({tag:'td',align:'center',valign:'top',style:'padding-top : 20px;',cls:'roo-m-column-container'});}return this.el.select('.roo-m-'+this.blocktype+'-content',true).first();}});
//Roo/mailer/BodyContainer.js
Roo.mailer.BodyContainer=function(A){Roo.mailer.BodyContainer.superclass.constructor.call(this,A);};Roo.extend(Roo.mailer.BodyContainer,Roo.bootstrap.Component,{cls:'',getAutoCreate:function(){var A={tag:'table',border:0,cellpadding:0,cellspacing:0,cls:'roo-m-body-container '+this.cls};return A;},getChildContainer:function(){var tr=this.el.createChild({tag:'tr',cn:[{tag:'td',align:'center',valign:'top',cls:'roo-m-child-ctr'}]});return tr.select('.roo-m-child-ctr').first();}});
//Roo/mailer/Column.js
Roo.mailer.Column=function(A){Roo.mailer.Column.superclass.constructor.call(this,A);};Roo.extend(Roo.mailer.Column,Roo.bootstrap.Component,{cls:'',html:'',src:'',column:'left',getAutoCreate:function(){var tr={tag:'tr',cn:[]};var cfg={tag:'table',border:0,cellpadding:20,cellspacing:0,width:'100%',cn:[]};if(this.src!=''){cfg.cn.push({tag:'tr',cn:[{tag:'td',align:'center',valight:'top',cls:'roo-m-column-'+this.column+'-content',cn:[{tag:'img',src:this.src,cls:'roo-m-column-image',style:'max-width: 260px;'}]}]});}
cfg.cn.push({tag:'tr',cn:[{tag:'td',align:'center',valight:'top',cls:'roo-m-column-'+this.column+'-content roo-m-column-body',html:this.html}]});return cfg;},getChildContainer:function(){return this.el.select('.roo-m-column-body',true).first();}});
